name: frontend ci test


on:
    push:
        branches: [ "main" ]
        paths: [ "client/**" ]
    pull_request:
        branches: [ "main" ]
        paths: [ "client/**" ]


jobs:
    test_frontend:
        runs-on: ubuntu-latest
        
        steps:
            - name: pull frontend code
              uses: actions/checkout@v4
            
            - name: set up node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: npm
                  cache-dependency-path: client/package-lock.json

            - name: Install dependencies
              working-directory: client
              run: npm ci

            - name: Run lint
              working-directory: client
              run: npm run lint 
            
            - name: Check code format
              working-directory: client
              run: npm run format:check

            - name: Build
              working-directory: client
              run: npm run build
